const CartActionTypes = {
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM_FROM_CARTITEMS_ARRAY: "REMOVE_ITEM_FROM_CARTITEMS_ARRAY",
  DELETE_QUANTITY_CARTITEMS_ARRAY: "DELETE_QUANTITY_CARTITEMS_ARRAY",
};

export default CartActionTypes;
